# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

class ServoClient:
    def __new__(cls,): ...
    def wait_closed(self) -> None:
        ...

    def pingx2(self, id:builtins.int) -> builtins.int:
        ...

    def get_id(self) -> builtins.int:
        ...

    def set_angle(self, angle:builtins.int) -> None:
        ...

    def get_angle(self) -> builtins.int:
        ...


