[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
dotenvy = { workspace = true }
rust-s3 = { version = "0.35.1", default-features = false, features = ["sync", "sync-native-tls"] }
