[package]
name = "protocol"
version.workspace = true
edition.workspace = true

[dependencies]
postcard-rpc = { version = "0.11.9" }
postcard-schema = { version = "0.2.1", features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
use-std = []
