# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

class ServoClient:
    r"""
    This class communicates with Bluepill Servo Rust firmware.
    """
    def __new__(cls,): ...
    def wait_closed(self) -> None:
        ...

    def pingx2(self, id:builtins.int) -> builtins.int:
        r"""
        Send a ping to the board and return the response.
        A number is sent to the device, and the device is expected to return the same number times 2.
        """
        ...

    def get_id(self) -> builtins.int:
        r"""
        Get the unique ID of the board.
        The ID is a 92-bit number, which is padded to 128 bits with zeros.
        """
        ...

    def set_angle(self, angle:builtins.int) -> None:
        r"""
        Set the angle of the servo.
        The angle is a number between 0 and 180.
        """
        ...

    def get_angle(self) -> builtins.int:
        r"""
        Get the angle of the servo.
        The angle is a number between 0 and 180.
        """
        ...


